### PR TITLE
release 3.0.0

### LINKED ISSUE #43: Add python 3.9 support

### LINKED ISSUE #44: Remove python 3.4 support
Going to consider this a non-breaking change. The code should continue to work on 3.4, but we don't want to officially support it anymore, since it's EOL.

### PR DESCRIPTION
**Pull request by JeffreyLMelvin**
Update version. Includes
- https://github.com/zach-taylor/splunk_handler/pull/51
- https://github.com/zach-taylor/splunk_handler/pull/49
- https://github.com/zach-taylor/splunk_handler/pull/47

@zach-taylor

### CODE REVIEW

**Comment by zach-taylor** [comment]
@AetherDeity I forgot to remove the travis config, the tests run on GitHub actions now. can you update the GitHub test workflow and delete the travis config?

**Comment by AetherDeity** [comment]
Done @zach-taylor

**Comment by zach-taylor** [comment]
@AetherDeity I'm not super familiar with splunk anymore, but I suppose it _could_ cause something to break. I just noticed python 3.4 AND 3.5 are EOL, so let's remove those from setup.py and 3.5 from the tests and call this v3.0.0.

**Comment by AetherDeity** [comment]
@zach-taylor , I dont think there are any breaking changes, unless someone is running old splunk and doesnt have the new endpoint, which was why I thought a minor version would be good. But I agree this seems like a good opportunity to remove EOL python (included 2.7) and cut a major release.

**Review by zach-taylor — APPROVED** [review]
Awesome, thanks! I will release this on pypi shortly

**Pull request merged**
